version: '3.7'
services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger-local
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
    volumes:
        - jaeger-volume:/var
    networks:
      - jaeger-network

networks:
  jaeger-network:
    driver: bridge

volumes:
  jaeger-volume:
    external: false
